service: octopus-garden

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  profile: pelagos-service
  region: eu-central-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: octopus-garden
      # https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html
      statements:
        -
          Effect: Allow
          Action:
            - 'ssm:DescribeParameters'
          Resource: '*'
        -
          Effect: Allow
          Action:
            - 'ssm:GetParameter'
          Resource: 'arn:aws:ssm:eu-central-1::parameter/octopus_garden_*'

plugins:
  - serverless-offline

package:
  excludeDevDependencies: false

functions:
  circulation:
    memorySize: 1024
    timeout: 29
    handler: handler.circulation
    environment:
      # https://www.serverless.com/blog/aws-secrets-management
      # https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-using-the-ssm-parameter-store
      # https://eu-central-1.console.aws.amazon.com/systems-manager/parameters
      vested_count: ${ssm:/octopus_garden_vested_count}
      vested_sum: ${ssm:/octopus_garden_vested_sum}
    events:
      -
        http: 
          path: circulation
          method: get
          cors: true
  vested:
    memorySize: 1024
    timeout: 29
    handler: handler.vested
    events:
      -
        http: 
          path: balances/vested
          method: get
          cors: true
