service: octopus-garden

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  profile: pelagos-service
  region: eu-central-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

package:
  excludeDevDependencies: false

functions:
  circulation:
    memorySize: 1024
    timeout: 29
    handler: handler.circulation
    events:
      -
        http: 
          path: circulation
          method: get
          cors: true
  accounts:
    memorySize: 1024
    timeout: 29
    handler: handler.accounts
    events:
      -
        http: 
          path: accounts
          method: get
          cors: true
