service: octopus-garden

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  profile: pelagos-service
  region: eu-central-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: octopus-garden
      # https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html
      statements:
        -
          Effect: Allow
          Action:
            - 'ssm:DescribeParameters'
          Resource: '*'
        -
          Effect: Allow
          Action:
            - 'ssm:GetParameter'
          Resource: 'arn:aws:ssm:eu-central-1::parameter/octopus_garden_*'

plugins:
  - serverless-offline
useDotenv: true

package:
  excludeDevDependencies: true

functions:
  circulation:
    memorySize: 1024
    timeout: 29
    handler: handler.circulation
    events:
      -
        http:
          path: circulation
          method: get
          cors: true
  candidatePool:
    timeout: 29
    environment:
      octopus_garden_db_read: ${ssm:/octopus_garden_db_read}
    handler: collation.list
    events:
      -
        http:
          path: collators
          method: get
          cors: true
  candidateInfo:
    timeout: 29
    environment:
      octopus_garden_db_read: ${ssm:/octopus_garden_db_read}
    handler: collation.info
    events:
      -
        http:
          path: collator/{account}/info
          method: get
          cors: true
          request:
            parameters:
               paths:
                 account: true
  candidateHistory:
    timeout: 29
    environment:
      octopus_garden_db_read: ${ssm:/octopus_garden_db_read}
    handler: collation.history
    events:
      -
        http:
          path: collator/{account}/history
          method: get
          cors: true
          request:
            parameters:
               paths:
                 account: true
  stakingRound:
    timeout: 29
    environment:
      octopus_garden_db_read: ${ssm:/octopus_garden_db_read}
    handler: collation.round
    events:
      -
        http:
          path: staking/round
          method: get
          cors: true
